### ISSUE TITLE
qml背景透明

### ISSUE THREAD

**Issue by wpscott** [orzogc/acfundmj#1]
针对Windows平台，需要在flags加一个`| Qt.WA_TranslucentBackground`

**Comment by orzogc** [comment]
现在的问题是加了Qt.WA_TranslucentBackground后背景是透明了，但是会导致程序不会出现在任务栏那里，obs无法捕捉其窗口，只能全屏捕捉，大佬有解决的办法吗？

**Comment by wpscott** [comment]
很奇怪，之前我是在本地试验过没问题才提的issue，今天再试就不行了。

**Comment by orzogc** [comment]
不需要设置`WA_TranslucentBackground`，obs里添加游戏捕获->捕获特定窗口->选择弹幕姬->允许透明度->确定，等待几分钟就能捕获到背景透明的弹幕姬
